root: true
env:
  es2020: true
  browser: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:react/recommended"
  - "plugin:react/jsx-runtime"
  - "prettier"
plugins:
  - "@typescript-eslint"
  - "prettier"
  - "react-refresh"
ignorePatterns:
  - ".eslintrc.yml"
  - "**/generated/**/*"
  - "dist"
parserOptions:
  ecmaVersion: "latest"
  sourceType: "module"
settings:
  react:
    version: "18.2"
rules:
  "@typescript-eslint/interface-name-prefix": "off"
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/ban-ts-comment": "warn"
  "@typescript-eslint/no-unused-vars":
    ["error", { "argsIgnorePattern": "^_", "varsIgnorePattern": "^_" }]
  "react-refresh/only-export-components":
    ["warn", { "allowConstantExport": true }]
  quotes:
    - error
    - double
  semi:
    - error
    - never
  no-console: 2
